//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CptDash
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employee
    {
        public Employee()
        {
            this.BidLinePerPeriods = new HashSet<BidLinePerPeriod>();
            this.Reports = new HashSet<Report>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public Nullable<int> Number { get; set; }
    
        public virtual ICollection<BidLinePerPeriod> BidLinePerPeriods { get; set; }
        public virtual ICollection<Report> Reports { get; set; }
    }
}
