//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CptDash
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class CptDashEntities : DbContext
    {
        public CptDashEntities()
            : base("name=CptDashEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<BidLinePerPeriod> BidLinePerPeriods { get; set; }
        public virtual DbSet<BidLine> BidLines { get; set; }
        public virtual DbSet<Category> Categories { get; set; }
        public virtual DbSet<DailyPayment> DailyPayments { get; set; }
        public virtual DbSet<Employee> Employees { get; set; }
        public virtual DbSet<Period> Periods { get; set; }
        public virtual DbSet<Report> Reports { get; set; }
    }
}
